import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">APIs!</a>
        </h1>

        <p className={styles.description}>
          Editing APIs in
          <code className={styles.code}>api</code>
          directory
        </p>

        <div className={styles.grid}>
          <a href="/api/login" className={styles.card}>
            <h2>Login &rarr;</h2>
          </a>
          <a href="/api/logout" className={styles.card}>
            <h2>Logout &rarr;</h2>
          </a>
          <a href="/api/delete-order" className={styles.card}>
            <h2>Delete-Order &rarr;</h2>
          </a>
          <a href="/api/add-product-department" className={styles.card}>
            <h2>Add-Product-Department &rarr;</h2>
          </a>
          <a href="/api/get-products" className={styles.card}>
            <h2>Get-Products &rarr;</h2>
          </a>
          <a href="/api/get-product" className={styles.card}>
            <h2>Get-Product &rarr;</h2>
          </a>
          <a href="/api/add-product" className={styles.card}>
            <h2>Add-Product &rarr;</h2>
          </a>
          <a href="/api/get-users" className={styles.card}>
            <h2>Get-Users &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>Powered by M.PirJamaat</footer>
    </div>
  );
}
